name: Publish to NPM
on:
  release:
    types: [created]
jobs:
  build-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set version from tag
        id: trim
        run: echo "version=${GITHUB_REF_NAME#v}" >> $GITHUB_OUTPUT
        
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          registry-url: 'https://registry.npmjs.org'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Install JSON utility
        run: npm install -g json
        
      - name: Update version in package files
        run: |
          json -I -f package.json -e "this.version=\"${{ steps.trim.outputs.version }}\""
          json -I -f package-lock.json -e "this.version=\"${{ steps.trim.outputs.version }}\""
          
      - name: Build package
        run: npm run build
        
      - name: Create package
        run: npm pack
        
      - name: Publish @next
        if: github.event.release.prerelease
        run: npm publish --tag next
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}
          
      - name: Publish @latest
        if: "!github.event.release.prerelease"
        run: npm publish --tag latest
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}
